### ISSUE TITLE
Abbildung 8.4 falsch?

### ISSUE THREAD

**Issue by NMarkgraf** [sebastiansauer/statistik1#1]
Ich weiß ja nicht, aber ist das erste und das dritte Bild hier bei der Abbildung 8.4 vertauscht?

**Comment by sebastiansauer** [comment]
ja, danke! ein hoch auf den aufmerksamen Beobachter

**Comment by sebastiansauer** [comment]
Fixed.

**Comment by sebastiansauer** [comment]
commit id #
